#ifndef X64_INCLUDE_X64_H
#define X64_INCLUDE_X64_H

#include "src/assembler.h"
#include "src/cfg.h"
#include "src/code.h"
#include "src/constants.h"
#include "src/cr.h"
#include "src/dr.h"
#include "src/eflag.h"
#include "src/function.h"
#include "src/hint.h"
#include "src/imm.h"
#include "src/instruction.h"
#include "src/label.h"
#include "src/m.h"
#include "src/mm.h"
#include "src/modifier.h"
#include "src/moffs.h"
#include "src/op_set.h"
#include "src/op_type.h"
#include "src/opcode.h"
#include "src/operand.h"
#include "src/properties.h"
#include "src/r.h"
#include "src/rel.h"
#include "src/sreg.h"
#include "src/stream.h"
#include "src/st.h"
#include "src/xmm.h"
#include "src/ymm.h"

#endif
